//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLTimer.Shared.WebsiteLocResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebsiteLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebsiteLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLTimer.Shared.WebsiteLocResources.WebsiteLoc", typeof(WebsiteLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill projects.
        /// </summary>
        public static string BillProjects {
            get {
                return ResourceManager.GetString("BillProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The REGIOS Association has prepared an Electoral Compass in which we have gathered information about the approaches of various electoral committees participating in the parliamentary elections of 2023 regarding the demand for the Silesian language and the recognition of Silesians as an ethnic minority. We encourage you to familiarize yourself with its content..
        /// </summary>
        public static string CompassDescription {
            get {
                return ResourceManager.GetString("CompassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline broken by.
        /// </summary>
        public static string DeadlineBrokenBy {
            get {
                return ResourceManager.GetString("DeadlineBrokenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the election campaign, many politicians, especially those running from Silesia, addressed demands related to the unrecognized Silesian minority and its language. Below are collected political declarations of the leaders of the so-called &quot;democratic opposition&quot; who signed a coalition agreement and declare the ability to form a majority government. One of these demands, the &quot;Radzionków Declaration,&quot; entails the recognition of the Silesian language as a regional language within the first 100 days of the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open letter.
        /// </summary>
        public static string OpenLetter {
            get {
                return ResourceManager.GetString("OpenLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the election campaign, the Silesian people had the opportunity to listen to promises made by various politicians. However, the time has come not only to listen but also to be heard. Therefore, we address Prime Minister Donald Tusk with an open letter requesting recognition of the Silesian minority and the Silesian language..
        /// </summary>
        public static string OpenLetterDescription {
            get {
                return ResourceManager.GetString("OpenLetterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promises.
        /// </summary>
        public static string Promises {
            get {
                return ResourceManager.GetString("Promises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Silesians.
        /// </summary>
        public static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
    }
}
